### ISSUE TITLE
Network disconnection crashes app when WebSocket is connected

### ISSUE THREAD

**Issue by ArtRoman** [korlibs/korio#102]
Application crashes If network connection breaks during websocket session. 
Reproduces on Android 10 immediately, on Android 7 it takes about 20 minutes before triggering `java.net.SocketException: Connection timed out`

On Android 10 stopping websocket-server causes 
```
AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
AndroidRuntime: Process: ***, PID: 4914
AndroidRuntime: java.net.SocketException: Connection reset
AndroidRuntime: 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
AndroidRuntime: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
AndroidRuntime: 	at com.soywiz.korio.net.JvmAsyncClient$read$2$invokeSuspend$$inlined$doIo$1.invokeSuspend(asyncSocketFactoryAndroid.kt:73)
AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

and disabling wifi (with disabled mobile network) causes 
```
AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
AndroidRuntime: Process: ***, PID: 6897
AndroidRuntime: java.net.SocketException: Software caused connection abort
AndroidRuntime: 	at java.net.SocketInputStream.socketRead0(Native Method)
AndroidRuntime: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
AndroidRuntime: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
AndroidRuntime: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
AndroidRuntime: 	at com.soywiz.korio.net.JvmAsyncClient$read$2$invokeSuspend$$inlined$doIo$1.invokeSuspend(asyncSocketFactoryAndroid.kt:73)
AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Error comes to system error log, then to my wsClient.onError handler, then it crashes the app. 
There are no my classes in stacktrace, so I can't catch error because CoroutineScheduler passes it to thread.uncaughtExceptionHandler.

**Comment by ArtRoman** [comment]
The issue was that "onError" callback was trying to close websocket on any error, and exactly the `wsClient?.close` call makes korio  to send another WsFrame to already closed socket. This produces error that can't be catched via try-catch, but only by coroutineExceptionHandler. Adding this in the right place resolves the issue. 

```Kotlin
private val coroutineExceptionHandler = CoroutineExceptionHandler { _, exception ->
    Log.e("coroutineExceptionHandler got $exception")
}

suspend fun connect(url: String){
    try {
        // Run this in separate coroutine because korio holds it while connection is active
        GlobalScope.launch(coroutineExceptionHandler) {
            wsClient = WebSocketClient(url)
            wsClient!!.onError.add { onError(it) }
           // Other handlers here…
        }
    } catch (e: Exception) {
        // process connection exceptions here
    }
}

private fun onError(error: Throwable) {
    Log.e("onError got $error")
    // Process error and try to disconnect
    wsClient?.close(WebSocketClient.CloseReasons.NORMAL, "disconnect")
}
```
