### ISSUE TITLE
How to cancel AsyncClient.read()?

### ISSUE THREAD

**Issue by paumove** [korlibs/korio#107]
In a multiplatform project, I am using the AsyncClient class to communicate with a socket with a proprietary protocol. 

I launch two coroutines: one for reading and one for writting. The reading coroutine is a loop similar to this:

```
val asyncClient =  AsyncClient.createAndConnect("127.0.0.1", 12345, false)
//...
val readingJob = GlobalScope.launch {
    do {
        val buffer = ByteArray(1024)
        val bytesRead = asyncClient.read(buffer)
        //...process buffer
    } while(keepReading)
}
```

When I want to finish the communication I don't know exactly how to finish the reading process. When I close the AsyncClient, the AsyncClient.read() function returns a "Socket closed" exception that I cannot handle.

```
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:982)
	at com.soywiz.korio.net.JvmAsyncClient$read$2$invokeSuspend$$inlined$doIo$1.invokeSuspend(asyncSocketFactoryJvm.kt:77)
	(Coroutine boundary)
	at com.soywiz.korio.net.JvmAsyncClient$read$2.invokeSuspend(asyncSocketFactoryJvm.kt:77)
	at com.soywiz.korio.async.AsyncThread$sync$promise$1.invokeSuspend(AsyncQueue.kt:90)
	at com.soywiz.korio.async.AsyncExtKt$_async$1.invokeSuspend(AsyncExt.kt:50)
	(Coroutine creation stacktrace)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:186)
	at kotlinx.coroutines.BuildersKt.async(Unknown Source)
	at com.soywiz.korio.async.AsyncExtKt._async(AsyncExt.kt:48)
	at com.soywiz.korio.async.AsyncExtKt.asyncImmediately(AsyncExt.kt:14)
	at com.soywiz.korio.async.AsyncExtKt.asyncImmediately(AsyncExt.kt:23)
	at com.soywiz.korio.async.AsyncThread.sync(AsyncQueue.kt:88)
	at com.soywiz.korio.async.AsyncThread.invoke(AsyncQueue.kt:75)
	at com.soywiz.korio.net.JvmAsyncClient.read(asyncSocketFactoryJvm.kt:50)
	at com.soywiz.korio.stream.AsyncStreamKt.read(AsyncStream.kt:438)
	...
```

How can I control this problem? Wich's the correct way to cancel the asyncClient.read() prior to asyncClient.close()?

Thanks so much

**Comment by soywiz** [comment]
Can't you do a try { } catch {} inside the launch method?

**Comment by paumove** [comment]
Sorry, I did not indicate it in the example code but any type of try / catch does not work, the result is the same.

If I use a CoroutineExceptionHandler on launch, I can catch the exception, but the error is also fired.

I am attaching a test file so you can test it.
[AsyncClientTest.zip](https://github.com/korlibs/korio/files/5369864/AsyncClientTest.zip)

I am wondering if it might be related to the context of the coroutine and the propagation of the exceptions as explained here: https://kotlinlang.org/docs/reference/coroutines/exception-handling.html#exception-propagation

**Comment by soywiz** [comment]
Have you tried to call launch using the current coroutineContext? Does it work without launching?

**Comment by soywiz** [comment]
I'll check after 2.0

**Comment by soywiz** [comment]
This is the interface:
https://github.com/korlibs/korio/blob/ee950bbd5591e8da6b623a3bee8dc81e69a8c293/korio/src/commonMain/kotlin/com/soywiz/korio/net/AsyncSocketFactory.kt#L24-L46

Would you prefer a Signal that triggers on disconnection? I thought that the read throws an exception that can be captured.

**Comment by paumove** [comment]
> Have you tried to call launch using the current coroutineContext? 

I don't know exactly what you mean ... Using the example I posted, I have tried the following with the same result:

```
...
val readingJob = launch(handler) { //this uses the coroutineContext of runBlocking
...
```

> Does it work without launching?

If I don't use launch() it will get stuck in the read() and I won't have the option to call close().

**Comment by ArtRoman** [comment]
> val readingJob = launch(handler) { //this uses the coroutineContext of runBlocking

In my case adding coroutineExceptionHandler in correct 'launch' call resolves the issue, thanks! Try-catch is stil missing the exception.

**Comment by soywiz** [comment]
Note from @ArtRoman when reviewing this: https://github.com/korlibs/korio/issues/102#issuecomment-713287276
I think we should either make this more resilient, or state stuff in the documentation. Didn't investigate in the issue yet, but I'm pretty sure we can improve this so it is less confusing somehow. Thanks for your feedback and all the info that will help with the issue 👍  As commented already, this is delayed after 2.0 of the libraries, but will check.
