### ISSUE TITLE
Can't rename between filesystems.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#124]
When I try to rename a file twice with a button, I get the above error.

```kotlin
var file0 = "foo.txt"
var file1 = "bar.txt"
roundRect(100.0, 100.0, 0.0).onClick {
     resourceVfs.rename(file0, file1)
     file0.run {
        file0 = file1
        file1 = this
     }
}
```
Error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Can't rename between filesystems. Use copyTo instead, and remove later.
	at com.soywiz.korio.file.Vfs$Proxy.rename$suspendImpl(Vfs.kt:188)
	at com.soywiz.korio.file.Vfs$Proxy.rename(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.renameTo(VfsFile.kt:135)
	at com.soywiz.korio.file.Vfs$Proxy.rename$suspendImpl(Vfs.kt:189)
	at com.soywiz.korio.file.Vfs$Proxy.rename(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.renameTo(VfsFile.kt:135)
	at com.soywiz.korio.file.Vfs$Proxy.rename$suspendImpl(Vfs.kt:189)
	at com.soywiz.korio.file.Vfs$Proxy.rename(Vfs.kt)
	at Mod$start$1.invokeSuspend(main.kt:144)
	at Mod$start$1.invoke(main.kt)
	at Mod$start$1.invoke(main.kt)
	at com.soywiz.korio.async.RunBlockingNoSuspensionsKt.startCoroutineUndispatched(runBlockingNoSuspensions.kt:52)
	at com.soywiz.korio.async.RunBlockingNoSuspensionsKt.runBlockingNoSuspensions(runBlockingNoSuspensions.kt:19)
...
```

**Comment by Josef-Vonasek** [comment]
A workaround is to instead use:
```kotlin
            var file = resourceVfs[file0]
            if (file.exists()) {
                file.copyTo(dir[file1])
                delay(1000)
                file.delete(file0)
            }
```

**Comment by Josef-Vonasek** [comment]
Is `rename` using `copyTo` & `delete` under the hood? I don't think it should, because `rename` is `O(1)`, while `copy` is `O(N)`.

**Comment by soywiz** [comment]
resourcesVfs is a special vfs since sometimes it acecesses a jar file, and/or multiple folders. You dhould try localVfs instead

**Comment by Josef-Vonasek** [comment]
If I use `localCurrentDirVfs`, then `rename` operation deletes the renamed file, instead of renaming it.

**Comment by Josef-Vonasek** [comment]
LocalVfs works well, except the following issue:
```kotlin
val resources = localCurrentDirVfs["src/commonMain/resources"]
resources.rename("foo.txt", "bar.txt")
```
The above code will move `cwd/src/commonMain/resources/foo.txt` to `cwd/bar.txt`.
