### ISSUE TITLE
`ZipVfs` out of heap space.

### ISSUE THREAD

**Issue by Josef-Vonasek** [korlibs/korio#132]
I tried to unzip a 1GB ZIP file with `ZipVfs` and the following code:
```kotlin
val data = ZipVfs(dir["archive.zip"].open())
for (name in data.listNames()) {
    data[name].copyTo(dir["archive::$name"])
}
```
However, this crashed with out of memory error:
```kotlin
java.lang.OutOfMemoryError: Java heap space
	at com.soywiz.kmem.ByteArrayBuilder.<init>(ByteArrayBuilder.kt:10)
	at com.soywiz.korio.compression.CompressionMethodKt.uncompress(CompressionMethod.kt:56)
	at com.soywiz.korio.compression.CompressionMethodKt.uncompress$default(CompressionMethod.kt:49)
	at com.soywiz.korio.file.std.ZipVfsKt$ZipVfs$Impl.open(ZipVfs.kt:64)
	at com.soywiz.korio.file.Vfs.openInputStream$suspendImpl(Vfs.kt:65)
	at com.soywiz.korio.file.Vfs.openInputStream(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.openInputStream(VfsFile.kt:69)
	at com.soywiz.korio.file.VfsFile.copyTo(VfsFile.kt:57)
	at Mod$download$2.invokeSuspend(main.kt:188)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at com.soywiz.kmem.ByteArrayBuilder.<init>(ByteArrayBuilder.kt:10)
	at com.soywiz.korio.compression.CompressionMethodKt.uncompress(CompressionMethod.kt:56)
	at com.soywiz.korio.compression.CompressionMethodKt.uncompress$default(CompressionMethod.kt:49)
	at com.soywiz.korio.file.std.ZipVfsKt$ZipVfs$Impl.open(ZipVfs.kt:64)
	at com.soywiz.korio.file.Vfs.openInputStream$suspendImpl(Vfs.kt:65)
	at com.soywiz.korio.file.Vfs.openInputStream(Vfs.kt)
	at com.soywiz.korio.file.VfsFile.openInputStream(VfsFile.kt:69)
	at com.soywiz.korio.file.VfsFile.copyTo(VfsFile.kt:57)
	at Mod$download$2.invokeSuspend(main.kt:188)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Josef-Vonasek** [comment]
The issue seems that `ZipVfs.kt:64` attempts to read whole content into `ByteArray`:
```kotlin
val compressed = compressedData.readAll().uncompress(method)
```
Any workaround before this gets fixed?

**Comment by soywiz** [comment]
As a workaround I guess you can copy that file into your project and modify it. Maybe you can remove the CRC check and change `compressedData.readAll().uncompress(method)` with `compressedData.uncompressed(method)`? (unchecked)

**Comment by Josef-Vonasek** [comment]
I have defined my own `ZipVfs` with removed CRT check and `readAll`. However, this broke unzipping on windows (Mingwx64).

The following code works fine on JVM, but never finishes copying the first file on Windows. 
If I switch my `ZipVfs` file with `korio` `ZipVfs, it will work on Windows just fine:
```kotlin
ZipVfs(file).listRecursive{ true }.collect {
    it.copyTo(dir[it.path])
}
```

**Comment by soywiz** [comment]
You can try to apply this patch somehow. I had to update other files too:

https://github.com/korlibs/korge-next/commit/512dcd60584d87eed18d6b83056aa7b228f8de17

Or use korge-next. Download the repo `./gradlew publishToMavenLocal` and using `2.0.0.999` as version for the artifacts including korge-gradle-plugin

**Comment by Josef-Vonasek** [comment]
So, I have tried the new version. However, I noticed extreme degradation of performance of `copyTo`.

1. With JVM, old `ZipVfs` `copyTo` copies ~100 MB/s or more.
2. On Windows, old `ZipVfs` `copyTo` copies ~15 MB/s max.
3. On Windows, new `ZipVfs` `copyTo` copies ~100 KB/s max!

**Comment by Josef-Vonasek** [comment]
Looks like the source of overhead is the `uncompress` method (both for `DeflateNative` and `DeflatePortable`).

**Comment by Kesanov** [comment]
Output of profile:
![image](https://user-images.githubusercontent.com/22682767/126485489-69426c91-3558-4226-9518-608c2d22f599.png)
![image](https://user-images.githubusercontent.com/22682767/126485750-fcf318fe-a4e2-41bc-bdba-12ff32709eb2.png)

Where `logtime` is a toplevel function `suspend fun logtime(msg: String, fn: suspend () -> Unit) { fn() }`.


I am a little surprised that I still see `suspend` in the callgraph, as I ran the code inside `runBlockingNoJs`. 
I thought that would remove any suspension points...
It might be related to https://github.com/korlibs/korge/issues/591.

**Comment by soywiz** [comment]
@Josef-Vonasek I have performed a huge performance improvement on korge-next. Can you try again your checks and put here the results? (JVM + native release)

**Comment by Josef-Vonasek** [comment]
I tried to compile the whole `korge-next` with `./gradlew publishToMavenLocal`. However, it takes more than hour and I keep getting this compile error:
```
> Task :korge-editor:compileKotlinMingwX64
e: D:\korge-next\korge-editor\build\platforms\nativeDesktop\entrypoint\main.kt: (4, 8): Unresolved reference: main
e: D:\korge-next\korge-editor\build\platforms\nativeDesktop\entrypoint\main.kt: (8, 14): No value passed for parameter 'args'
```
Is there a way to compile, publish and import only the modified `korio`?

**Comment by soywiz** [comment]
Probably all the other modules have been already published

**Comment by Josef-Vonasek** [comment]
Tested. It is much faster now: `10-15MB/s`. Still 10x slower than JVM, but fast enough for my use-case.

**Comment by soywiz** [comment]
Okay. Then let's keep this as resolved. Hopefully we will figure out the issue of native. It uses zlib by default, so it should be as fast as in the JVM, might be an issue related to some overhead somewhere else in coroutines, I/O or something.
Feel free to create a separate issue for that. This issue at least is fixed (the out of space).
