### ISSUE TITLE
Concurrency issues with resourcesVfs["IMAGE"].readBitmap() ?

### ISSUE THREAD

**Issue by emign** [korlibs/korio#34]
I use a code similar to this:

````
 override suspend fun initBody() {
        image = preInitializedBitmap ?: resourcesVfs[imageFile].readBitmapOptimized()
        width = image.width * scale
        height = image.height * scale
        shape = BoxShape(width = width, height = height)
        body = world.createBody(bd)
        fixture.density = density
        fixture.shape = shape
        fixture.friction = friction
        fixture.restitution = restitution
        body.createFixture(fixture)
        createView()
        body.setView(view)
    }



    override suspend fun createView() {
        view = Graphics().image(image) {
            position(x, y)
        }.scale(scale).anchor(.5, .5)
        view.apply {
            onOver {
                //writeInfo()
            }
        }
    }
````

which creates box2d bodies and applies an image to their view. It works well for 1-20 objects. But when I spawn 50 or 100 Bodies with the same image as view, some do really get displayed but then the program crashes:

> java.lang.IllegalStateException: Check failed.
	at org.jbox2d.dynamics.World.createBody(World.kt:1920)
	at engineEmi.Bodies.Image.initBody(Image.kt:41)
	at engineEmi.Bodies.Image$initBody$1.invokeSuspend(Image.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "kotlinx.coroutines.DefaultExecutor" java.lang.IllegalStateException: Check failed.
	at org.jbox2d.dynamics.World.createBody(World.kt:1920)
	at engineEmi.Bodies.Image.initBody(Image.kt:41)
	at engineEmi.Bodies.Image$initBody$1.invokeSuspend(Image.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)

**Comment by soywiz** [comment]
https://github.com/korlibs/kbox2d/blob/master/kbox2d/src/commonMain/kotlin/org/jbox2d/dynamics/World.kt

Cool, no line 1920: https://github.com/korlibs/kbox2d/blob/da90657957bb7b38416337533e420f559be97138/kbox2d/src/commonMain/kotlin/org/jbox2d/dynamics/World.kt

Wait for next version compiled against 1.3.60 to see if at least we can have proper line numbers

**Comment by soywiz** [comment]
Though my guess is that it is this `assert`:  https://github.com/korlibs/kbox2d/blob/da90657957bb7b38416337533e420f559be97138/kbox2d/src/commonMain/kotlin/org/jbox2d/dynamics/World.kt#L548

**Comment by emign** [comment]
I just saw, that its not the only Exception I get:

> java.lang.IllegalStateException: Check failed.
	at org.jbox2d.dynamics.Body.createFixture(Body.kt:1151)
	at engineEmi.Bodies.Image.initBody(Image.kt:46)
	at engineEmi.Bodies.Image$initBody$1.invokeSuspend(Image.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "kotlinx.coroutines.DefaultExecutor" java.lang.IllegalStateException: Check failed.
	at org.jbox2d.dynamics.Body.createFixture(Body.kt:1151)
	at engineEmi.Bodies.Image.initBody(Image.kt:46)
	at engineEmi.Bodies.Image$initBody$1.invokeSuspend(Image.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)

I will test it with the Kotlin 1.3.60 version when its available.
I also only have 1919 lines in world.kt :)

**Comment by soywiz** [comment]
Though my guess is that it is this `assert`:  https://github.com/korlibs/kbox2d/blob/da90657957bb7b38416337533e420f559be97138/kbox2d/src/commonMain/kotlin/org/jbox2d/dynamics/World.kt#L548

Also, it should be just a single thread or at least just one thread executing at a time, so shouldn't be a concurrency problem related to threads, maybe the `World` is in an inconsistent state just before doing a suspension for I/O then it is suspending and a frame occurs that updates the World?
But at any rate this issue shouldn't be related to korio at all; either kbox2d project or korge.
I can add a mechanism to suspend the world from updating while you are doing stuff

**Comment by emign** [comment]
I moved it [here](https://github.com/korlibs/korge/issues/45)
