### ISSUE TITLE
java.lang.NoSuchMethodError: com.soywiz.korio.net.ws.WebSocketsJvmKt

### ISSUE THREAD

**Issue by kirillkuvaldin** [korlibs/korio#43]
Hi Carlos,

Currently looking into your KorGE tutorials and trying to add a websocket into my game using korio. 

Here's the error message after the app starts
```
java.lang.NoSuchMethodError: com.soywiz.korio.net.ws.WebSocketsJvmKt.WebSocketClient$default(Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;ZLkotlin/coroutines/Continuation;ILjava/lang/Object;)Ljava/lang/Object;
	at MainScene.sceneInit(Main.kt:38)
	at com.soywiz.korge.scene.SceneContainer$_changeTo$3.invokeSuspend(SceneContainer.kt:118)
	at com.soywiz.korge.scene.SceneContainer$_changeTo$3.invoke(SceneContainer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
```

Here's my code:

```
class MainScene : Scene() {
    var ws:WebSocketClient? = null
    override suspend fun Container.sceneInit() {
        text("Hello there!")

        ws = WebSocketClient("ws://127.0.0.1:7777/ws/")
        val ws = ws!!

        ws.onBinaryMessage {
            val w = Wire.protoUnmarshal(it)
            println(w)
        }
        println("sending to ws...")
        ws.send(Wire(login = Login()).protoMarshal())
    }
}

```
inside the build.gradle file I have the following dependencies

```
		jvmCompile "com.soywiz.korlibs.korio:korio:1.9.8"
		jvmCompile "com.soywiz.korlibs.korio:korio-jvm:1.9.8"
```

**Comment by soywiz** [comment]
Does this still happen with the latest korge version `1.12.2.1`? Can you show your full `build.gradle`? When using Korge, you shouldn't include korio manually since korge already includes it

**Comment by soywiz** [comment]
Well it seems that you were using a custom port. So you had this issue: https://github.com/korlibs/korio/issues/53
And it is fixed now.
