### ISSUE TITLE
Opening Zip File tells "Not a zip file record 0xFFFFFFFF instead of 0x504B0102

### ISSUE THREAD

**Issue by danielgruber** [korlibs/korio#69]
When I try to open a ZIP file created on my mac it will tell:
Caused by: java.lang.IllegalStateException: Not a zip file record 0xFFFFFFFF instead of 0x504B0102
2020-05-13 02:17:23.411 15528-16050/? W/System.err:     at com.soywiz.korio.file.std.ZipVfsKt.ZipVfs(ZipVfs.kt:95)
2020-05-13 02:17:23.412 15528-16050/? W/System.err:     at com.soywiz.korio.file.std.ZipVfsKt.openAsZip(ZipVfs.kt:260)
2020-05-13 02:17:23.412 15528-16050/? W/System.err:     at com.soywiz.korio.file.std.ZipVfsKt.openAsZip(ZipVfs.kt:264)
2020-05-13 02:17:23.412 15528-16050/? W/System.err:     at com.soywiz.korio.file.std.ZipVfsKt.openAsZip$default(ZipVfs.kt:263)

What can I do about it? Thanks :)

**Comment by soywiz** [comment]
Which program are you using?
And can you attach a small file reproducing it? For example with a small txt file inside or something. That would help since I could add it as a test.

**Comment by danielgruber** [comment]
I had a problem how I imported the file into the Android App, so no Bug here, thanks!
